### ISSUE TITLE
problem with wash 

### ISSUE THREAD

**Issue by ghost** [jgilhutton/pyxiewps#1]
The pyxiewps script runs fine but it seems that i have a problem with wash as you mentioned in the description. There was a new update recently for Kali that fixed some minor issues but has also changed the rules for aircrack-ng suite. Now instead of the regular mon0, i have to write in wlan0mon. I have also encountered a problem with wash where when i run wash ( wash -i wlan0mon) its gives me an fcs error which is fixable by adding the (--ignore-fcs) to the end of the wash command but since your script is automated, i suspect it runs wash as normal and the fcs error gets into the way of it. i tired running both script with and without aircrack and it just takes me to the " No wps-active found". Is there a way for me to just add the ignore fcs error for wash?

**Comment by jgilhutton** [comment]
I know about the mon0 wlan0mon thing and i'll check the fcs problem as soon as I can.
Be patient :) 
Juan Ignacio.

**Comment by jgilhutton** [comment]
Good news! The script will no longer use wash to enumerate the APs. It'll use Airodump.
I will upload the new version anytime soon.
Juan Ignacio.

**Comment by mw3demo** [comment]
Great news! Any update?

**Comment by jgilhutton** [comment]
Yes! I'll upload the new version this week.
Aircrack will no longer be used to set the monitor interface
Airodump will be used to enumerate the APs
Will support modes

I'll write a changelog and put it in the README file.
Stay tuned
