### ISSUE TITLE
Shell prompt hangs on exit of script.

### ISSUE THREAD

**Issue by ghost** [jgilhutton/pyxiewps#2]
Hello Dev Jgilhutton,

Thanks for the script :)

Problem description: As script ends, you would expect to retreive prompte on shell. But prompte does appear (root@kali:/home/pyxie_fork#) but no letters appear as you type on keyboard.

The enter key seems to make a difference, as when you hit enter, it validates all the hidden characters you just entered but could not see.

Quick reslolve: You need to end ssh session.

Config / Setup:
OS: Kali linux for Raspberry PI - v1.1.1
Wifi Adapter: Alfa AWUS036H - 54mb (b/g)

![untitled](https://cloud.githubusercontent.com/assets/10058545/8697218/a0c54fe0-2af3-11e5-8576-de5199762a63.jpg)

Sorry for spelling mistake, wrote this in a hurry.

Best regards,
BH

**Comment by ghost** [comment]
Please don't hesitate to ask for missing information.

**Comment by jgilhutton** [comment]
Hello! I'm really really sorry for the wait!
I was aware of that problem when I uploaded the updated script but I didn't, and still don't, think that it is a huge problem.
Answering to your question, the problems seems to come from Airodump. Airodump's output gives a HUUUGE headache when you try to control and capture it for later use. You just have to read the parser for the ADump's output... pure mayhem.
But there is a quick solution for this problem, and it's a good way to retrieve the prompt on the console. Here it goes: The only thing you have to do is re-run the script and hit CTRL-C when it's looking for APs. Notice that by the time you hit CTRL-C, ADump is running on the background so, by killing it, you avoid the problem with the program eating up the prompt) I hope I made my self clear; if I did't please ask for a better explanation. english is not my mother language.
Good hunt!
Juan Ignacio
  The only

**Comment by ghost** [comment]
Hello Juan,

Thanks for the reply, I hear you clearly!

I successfully managed to end the script with the CTRL+C just as it starts searching for APs.
I fully retrieved the prompt on shell minor the python error at the end.

It tried this on a Kali linux x64 in VM on Intelx64 laptop.
Thanks.

Error msg if interrested:

```
[+] Enabling monitor mode on wlan0...
[+] Monitor mode enabled on wlan0

[+] Starting the attack...
[+] Enumerating WPS-active APs...      <------ HIT CTRL+C to kill script.

[!] Interrupted program!


[+] Restoring wlan0 wireless interface...
Traceback (most recent call last):
  File "pyxiewps-EN.py", line 987, in <module>
    engine.exit_clean()
  File "pyxiewps-EN.py", line 541, in exit_clean
    c.set_iface("DOWN")
  File "pyxiewps-EN.py", line 672, in set_iface
    system('ifconfig %s up' %(self.IFACE_MON))
  File "pyxiewps-EN.py", line 488, in alarm_handler
    raise Alarm
__main__.Alarm
root@Krasp:/home/pixie/pyxiewps-master# 
root@Krasp:/home/pixie/pyxiewps-master#
```

**Comment by jgilhutton** [comment]
Yup yup, that's because I set up a timed alarm to control the Airodump enumerating time.
Default amount of time is 3 seconds (1 second if channel is provided in the commandline). Before Airodump starts enumerating the APs, a timed alarm is set and clock starts ticking and more important... that alarm is GLOBAL. When you hit CTRL-C the script jumps to the exit_clean() function to set the interface back to Managed (Normal) mode but the time of the alarm is still ticking and if the script runs out of time, Python raises an exception in the set_iface() function called by exit_clean(). If this exception is raised when set_iface() is running, your interface could have troubles.
If the wireless interface is not brought back correctly:
-Do the same thing to bring back the prompt but with "-a 10". This gives pyxiewps a good time to exit clean.
-Manually bring back the interface with the following commands:
$> ifconfig <iface> down
$> iwconfig <iface> mode Managed
$> ifconfig <iface> up

I should reeeeeeeally write some lines in the script to help users in this one.
Good hunt!
Juan Ignacio

**Comment by jgilhutton** [comment]
Quick question...
Did you get something with it? 
If you don't want to say anything at all I get it but I'm also curious HaHa.

**Comment by ghost** [comment]
The wireless interface works fine after ending the script.

Sadly no, I've found nothing yet. Mostly because the script actually end unexpectedly. Sometimes it runs for 5 to 10 minutes, sometimes only for 2 minutes.

It's unclear to me yet why, but here are some considerations:
- The script is running on raspberry which is ARM.
- The raspberry is powered by XIAOMI 16000mAh battery using both USBs ports for maximum current.
- The raspberry has secondary wifi interface dongle for me to connect to it with Android phone using VNC client.

I'll try to post some error messages when I get some.

EDIT: I'm going to try with a laptop this time and put aside the Raspberry for the time being. Also your script is much easier to install than PixieScript 2.6.3. Thanks for that.

**Comment by jgilhutton** [comment]
Yes, please, give me that error messages :D 
Good hunt!
Juan Ignacio

**Comment by jgilhutton** [comment]
GOOD NEWS!
I found the problem with the prompt!
Pyhon no longer handles the end of the Airodump process. Bash seems to handle it much much better so i added a line calling "pkill airodump" and voila!
Check it out.
Juan Ignacio.

**Comment by ghost** [comment]
I'm going to test the new fix for pormpt. Be back soon.

EDIT: I've removed in this comment all issue referring to log file --output option and placed all the information is new issue.

**Comment by ghost** [comment]
Great work man, the prompt is back at work :)

It's more pleasure to use the script now
