### ISSUE TITLE
Log file option (-o --output) not working, file empty after scan.

### ISSUE THREAD

**Issue by ghost** [jgilhutton/pyxiewps#3]
Hello Juan,

Please allow me to create this new issue for this instead of using email.

Error description: When executing script with option log ouput (-o --ouput), we are expecting to find a file with content inside, but the file is empty.

Test 1: Do not create file and run script with --ouput of new file not existent yet.
Result 1: No file created :(

test 2: Create txt file at root of script, chmod 755, run script with --output of file existent.
Result 1: File exist of course but file is empty although script reported mutiple APs

EDIT: please bellow my orignal comment which I moved here from issue about prompte:

I've just tried the fix for --output option for log file and doesn't seem to work.

cat output-1.txt return nothing. File is empty. Tried the same with a subfolder for output file and still doesn't work. Checked all files are chmoded 755.

```
root@Krasp:/home/pixie/pyxiewps-master# ls
CHANGELOG.md  LICENSE  pyxiewps-EN.py  pyxiewps-ES.py  README.md  Version-1.0
root@Krasp:/home/pixie/pyxiewps-master# touch output-1.txt
root@Krasp:/home/pixie/pyxiewps-master# python pyxiewps-EN.py --output output-1.txt

     ____             _                         
    |  _ \ _   ___  _(_) _____      ___ __  ___ 
    | |_) | | | \ \/ / |/ _ \ \ /\ / / '_ \/ __|
    |  __/| |_| |>  <| |  __/\ V  V /| |_) \__ \
    |_|    \__, /_/\_\_|\___| \_/\_/ | .__/|___\
           |___/                     |_|        

    Pyxiewps v1.1 by jgilhutton <pyxiewps@gmail.com>
    Reaver 1.5.2 mod by t6_x <t6_x@hotmail.com> & DataHead & Soxrok2212 & Wiire & kib0rg
     Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
    Pixiewps  Copyright (c) 2015, wiire <wi7ire@gmail.com>
    Aircrack www.aircrack-ng.org

[+] Enabling monitor mode on wlan0mon...
[+] Monitor mode enabled on wlan0mon

[+] Starting the attack...
[+] Enumerating WPS-active APs...
[+] The following WPS-active APs were found:
    [>] SFR_XX || 24:95:04:xx:xx:xx || Channel: 01 || RSSI: -63 || WPS: 1.0
    [>] Livebox-XX || C0:AC:54:xx:xx:xx || Channel: 01 || RSSI: -67 || WPS: 1.0
[+] Fetching information from SFR_XX using reaver...
[+] Success! All the needed information were found

[DATA] ESSID: SFR_XX
[DATA] MAC: XX:XX:XX:XX:XX:
[DATA] PKE: XX:XX:XX:XX:XX:
[DATA] PKR: XX:XX:XX:XX:XX:XX:XX:
[DATA] HASH1: XX:XX:XX:XX:XX:XX:XX:
[DATA] HASH2: XX:XX:XX:XX:XX:XX:XX:
[DATA] E-NONCE: XX:XX:XX:XX:XX:XX:XX:
[DATA] R-NONCE: XX:XX:XX:XX:XX:XX:XX:
[DATA] AUTHKEY: XX:XX:XX:XX:XX:XX:XX:
[DATA] MANUFACTURER: NB6V-SER-r0
[DATA] MODEL: NB6V-SER-r0
[DATA] MODEL NUMBER: NB6V-SER-r0

[+] All data were saved into output-1.txt


[+] Restoring wlan0mon wireless interface...
[+] Done
root@Krasp:/home/pixie/pyxiewps-master#

```

**Comment by ghost** [comment]
Alternative way for logging information from screen is to pipe linux command TEE.

python -u pyxiewps-EN.py | tee -a output.txt

Where -u is for unicode string output, and -a from Tee command is append.

**Comment by jgilhutton** [comment]
Completely weird. I have a fully working logging system. Fancy way to say that it works for me.
![screenshot from 2015-07-17 13 03 49](https://cloud.githubusercontent.com/assets/12903414/8751626/8ce64de8-2c84-11e5-84af-597a287b32f0.png)
Providing the -o or --output flag without giving any filename in particlar will save the information into a file named 'data.txt' in the root home directory.
Did you try to run the script with the -f -p flags so it tries to attack the AP? You can use -m to try a mode (much easier) and at the end append the -o|--output flag.
I also tried only with the -o flag so I got: $> python pyxiewps-EN.py -o and it saved the data without problems.
I think you know but, just in case I must say you that the script won't save any data if it doesn't found any. The key of the hole thing is to get the PKE,PRK, etc etc. If these things are not retrieved from the AP there will be nothing useful to save into the file

EDIT: if you use more than one flag try using -o first, just next to the .py of the file

**Comment by ghost** [comment]
Yeah I figured it wouldn't write anything to the file if no PKE,PKR were found. But did recover some PKE and PKR to fill up the file, but nothing.

I just used full path of file when using -o option, worked fine.

Thanks for this. RESOLVED
